// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocoalBufferRawDefinition

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protocoalBufferRawDefinition.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {


}  // namespace


void protobuf_AssignDesc_protocoalBufferRawDefinition() {
  protobuf_AddDesc_protocoalBufferRawDefinition();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protocoalBufferRawDefinition");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protocoalBufferRawDefinition);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_protocoalBufferRawDefinition() {
}

void protobuf_AddDesc_protocoalBufferRawDefinition() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\034protocoalBufferRawDefinition", 30);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protocoalBufferRawDefinition", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protocoalBufferRawDefinition);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protocoalBufferRawDefinition {
  StaticDescriptorInitializer_protocoalBufferRawDefinition() {
    protobuf_AddDesc_protocoalBufferRawDefinition();
  }
} static_descriptor_initializer_protocoalBufferRawDefinition_;

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
